name: Weighted PR Review Distribution
description: Automatically distributes PR reviews
author: Caleb Sharp
branding:
  icon: move
  color: green
inputs:
  repo-token:
    description: Github token secret
    required: true
  config:
    description: 'Path to config file'
    default: .github/reviewers.txt
runs:
  using: node12
  main: ./dist/index.js
